# Copilot Setup Steps for RPG-Gen Development
# This file contains setup instructions to work around infrastructure limitations

version: 1.0

# Problem: Cypress binary download blocked by firewall from download.cypress.io
# This prevents local E2E test execution in certain environments

workarounds:
  
  # Solution 1: Use GitHub Actions (Recommended)
  github_actions:
    description: "Execute E2E tests in GitHub Actions CI/CD where firewall restrictions don't apply"
    status: "✅ Already configured"
    file: ".github/workflows/cypress.yml"
    benefits:
      - "Automatic Cypress binary caching"
      - "Professional test artifacts (screenshots, videos)"
      - "No local firewall restrictions"
      - "Runs on every push and PR"
    usage:
      - "Push commits to trigger workflow"
      - "View results in GitHub Actions tab"
      - "Download test artifacts if tests fail"

  # Solution 2: Cypress Docker Image
  docker_approach:
    description: "Use official Cypress Docker image with pre-installed binary"
    status: "Alternative solution"
    docker_image: "cypress/included:13.6.0"
    steps:
      - step: "Pull Cypress Docker image"
        command: "docker pull cypress/included:13.6.0"
      - step: "Run tests in Docker container"
        command: |
          cd frontend
          docker run --rm \
            -v $PWD:/e2e \
            -w /e2e \
            --network host \
            cypress/included:13.6.0 \
            --config baseUrl=http://localhost:5173
      - step: "View test results"
        note: "Results will be in frontend/cypress/videos and frontend/cypress/screenshots"
    benefits:
      - "No binary download needed"
      - "Consistent testing environment"
      - "Works behind firewalls"

  # Solution 3: Manual Binary Installation
  manual_binary:
    description: "Manually download and install Cypress binary from a machine with unrestricted network"
    status: "Manual workaround"
    steps:
      - step: "On unrestricted machine, download Cypress binary"
        command: "npx cypress install"
      - step: "Locate Cypress cache directory"
        paths:
          linux: "~/.cache/Cypress"
          macos: "~/Library/Caches/Cypress"
          windows: "%LOCALAPPDATA%\\Cypress\\Cache"
      - step: "Copy entire Cypress directory to restricted machine"
        example: "scp -r ~/.cache/Cypress user@restricted-machine:~/.cache/"
      - step: "Verify installation on restricted machine"
        command: "npx cypress verify"
        expected: "Cypress executable verified"
      - step: "Run tests"
        command: "cd frontend && npm run test:e2e"

  # Solution 4: Firewall Whitelist Request
  firewall_whitelist:
    description: "Request IT to whitelist Cypress CDN domains"
    status: "Requires IT approval"
    domains_to_whitelist:
      - "download.cypress.io"
      - "*.cypress.io"
    justification: |
      Cypress is a widely-used E2E testing framework required for automated quality assurance.
      The binary download is necessary for local test execution and development.
      Alternative: Configure proxy or mirror for Cypress downloads.

# Current Test Status
test_status:
  backend:
    tests: "16/16 passing"
    command: "cd backend && npm test"
    status: "✅ Working"
  
  frontend_lint:
    command: "cd frontend && npm run lint"
    status: "✅ Working"
  
  frontend_build:
    command: "cd frontend && npm run build"
    status: "✅ Working"
  
  e2e_tests:
    total_tests: "45+ tests across 7 files"
    files:
      - "cypress/e2e/authentication.cy.ts (19 tests)"
      - "cypress/e2e/home.cy.ts (4 tests)"
      - "cypress/e2e/smoke.cy.ts (3 tests)"
      - "cypress/e2e/character-creation.cy.ts (6 tests)"
      - "cypress/e2e/world-selection.cy.ts (6 tests)"
      - "cypress/e2e/navigation.cy.ts (4 tests)"
      - "cypress/e2e/api-integration.cy.ts (3 tests)"
    status: "⚠️ Ready but blocked by binary download"
    workaround: "Use github_actions or docker_approach above"

# Quick Start (Recommended Approach)
quick_start:
  recommended: "Use GitHub Actions"
  steps:
    - "Commit and push your changes"
    - "GitHub Actions will automatically run all tests including E2E"
    - "View results at: https://github.com/alshyra/RPG-Gen/actions"
    - "Test artifacts available if tests fail"
  
  local_development:
    - "Run backend tests: cd backend && npm test"
    - "Run frontend lint: cd frontend && npm run lint"
    - "Run frontend build: cd frontend && npm run build"
    - "For E2E tests: Use Docker approach or manual binary installation"

# Verification Commands
verification:
  check_cypress_binary:
    command: "npx cypress verify"
    success: "Cypress executable verified"
    failure: "Binary not found or invalid - use workarounds above"
  
  check_cypress_cache:
    linux_mac: "ls -la ~/.cache/Cypress"
    windows: "dir %LOCALAPPDATA%\\Cypress\\Cache"
  
  test_e2e_with_docker:
    command: |
      cd frontend && \
      npm run dev & \
      sleep 5 && \
      docker run --rm -v $PWD:/e2e -w /e2e --network host \
        cypress/included:13.6.0 --config baseUrl=http://localhost:5173

# Additional Resources
resources:
  cypress_docs: "https://docs.cypress.io/guides/getting-started/installing-cypress"
  cypress_docker: "https://hub.docker.com/r/cypress/included"
  github_actions: "https://github.com/cypress-io/github-action"
  project_test_report: "E2E_TEST_REPORT.md"

# Notes
notes:
  - "All E2E tests are properly configured with auth mocking"
  - "Tests use cy.mockAuth(), cy.setupApiMocks() custom commands"
  - "API intercepts prevent backend timeouts"
  - "TypeScript compilation: 0 errors"
  - "Tests are production-ready, only infrastructure blocks local execution"
