services:
  mongodb:
    image: mongo:7.0
    container_name: rpg-gen-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rpgadmin
      MONGO_INITDB_ROOT_PASSWORD: rpgpass123
      MONGO_INITDB_DATABASE: rpggen
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - rpg-network

  backend:
    image: node:25.2.0-alpine3.22
    container_name: rpg-gen-backend
    restart: unless-stopped
    working_dir: /app
    user: "${UID}:${GID}"
    command: sh -c "npm --workspace rpg-gemini-backend run start"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://rpgadmin:rpgpass123@mongodb:27017/rpggen?authSource=admin
      - FRONTEND_URL=http://localhost
    volumes:
      - ./:/app/
      - backend_node_modules:/app/node_modules
    env_file:
      - packages/backend/.env
    depends_on:
      - mongodb
    networks:
      - rpg-network

  frontend:
    image: node:25.2.0-alpine3.22
    container_name: rpg-gen-frontend
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm --workspace rpg-gemini-frontend run dev"
    ports:
      - "80:80"
    user: "${UID}:${GID}"
    volumes:
      - ./:/app/
      - ./packages/frontend/nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf:ro
      - frontend_node_modules:/app/node_modules
    networks:
      - rpg-network
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  rpg-network:
    driver: bridge
