FROM node:25.2.0-alpine3.22 AS base_node
FROM base_node AS builder

WORKDIR /app
COPY . .

RUN npm ci
RUN npm --workspace @rpg-gen/backend run build

FROM base_node

WORKDIR /app/apps/backend

COPY --from=builder /app/ /app
ENV SCENARIO_PATH=/app/apps/backend/assets/scenarii/chat.scenario.txt
ENV TEMPLATE_PATH=/app/apps/backend/chat.prompt.txt
ENV NODE_ENV=production

EXPOSE 3001
ENTRYPOINT [ "npm" ]
CMD ["run", "start:prod"]
