FROM node:25-alpine

WORKDIR /app

COPY frontend/package*.json ./frontend/
COPY shared ./shared

WORKDIR /app/frontend
RUN npm install

COPY frontend ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
