FROM node:25.2.0-alpine3.22 AS builder

WORKDIR /app

COPY . .
RUN npm ci
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/apps/frontend/dist /usr/share/nginx/html
COPY apps/frontend/nginx/nginx.conf.prod /etc/nginx/conf.d/default.conf

RUN apk add --no-cache ca-certificates \
    && update-ca-certificates \
    && mkdir -p /etc/ssl/certs

EXPOSE 80
