FROM node:25.2.0-alpine3.22 AS base_node
FROM base_node AS builder

WORKDIR /app
COPY . .

RUN npm ci
RUN npm --workspace rpg-gemini-backend run build

FROM base_node

WORKDIR /app/packages/backend

COPY --from=builder /app/ /app
ENV TEMPLATE_PATH=/app/packages/backend/chat.prompt.txt

EXPOSE 3001
ENTRYPOINT [ "npm" ]
CMD ["run", "start:prod"]
